#ifndef _USER_COMMON_H_
#define _USER_COMMON_H_

// 识别板统一配置入口
// -----------------------------------------------------------------------------
// 当前主链口径：
// - 相机输入固定按 320x240 彩色图处理。
// - 软件层只保留 y=30..160 的有效区域，其余区域拿到单帧后直接清黑。
// - ROI 几何主链基于 white_reference_row_y=160 的白红参考包络、白带边线迷宫法、
//   严格红掩码和曲边赛道区域判定。
// - 六小类模型可在板端聚合成 weapon/supply/vehicle 三大类输出，串口仍输出 w/s/v。
//
// 组织原则：
// - 前面只放现场常调参数。
// - 自己不确定怎么调、通常不该动的参数，统一放到最后的“几乎不调”区。

#pragma region A. 现场常调：运行模式

// [先调] 图传编译期默认开关，可被 --stream / --no-stream 覆盖。
#ifndef BW_ENABLE_STREAM
// #define BW_ENABLE_STREAM 1
#define BW_ENABLE_STREAM 0
#endif

// [先调] 1：上电后等待按 c 启动；0：上电即持续运行识别链。
#ifndef BW_RECOG_REQUIRE_MANUAL_START
#define BW_RECOG_REQUIRE_MANUAL_START 0
#endif

#pragma endregion

#pragma region B. 现场常调：软件盲盒任务

// [先调] 软件盲盒任务选择。
// 0：关闭软件盲盒支链；1：色布发车。
#ifndef BW_SOFTWARE_BLIND_BOX_TASK_NONE
#define BW_SOFTWARE_BLIND_BOX_TASK_NONE 0
#endif

#ifndef BW_SOFTWARE_BLIND_BOX_TASK_COLOR_CLOTH_START
#define BW_SOFTWARE_BLIND_BOX_TASK_COLOR_CLOTH_START 1
#endif

#ifndef BW_SOFTWARE_BLIND_BOX_TASK
#define BW_SOFTWARE_BLIND_BOX_TASK 0
#endif

// [先调] 色布发车颜色。当前实现 GREEN：中心看到绿布时发停车状态，绿布消失恢复正常。
#ifndef GREEN
#define GREEN 1
#endif

#ifndef BW_CLOTH_COLOR_GREEN
#define BW_CLOTH_COLOR_GREEN GREEN
#endif

#ifndef BW_SOFTWARE_BLIND_BOX_CLOTH_COLOR
#define BW_SOFTWARE_BLIND_BOX_CLOTH_COLOR GREEN
#endif

// [先调] 色布发车中心检测窗口半宽/半高，作用于已经裁掉 y<30/y>=161 后的帧。
#ifndef BW_RECOG_CLOTH_CENTER_HALF_WIDTH
#define BW_RECOG_CLOTH_CENTER_HALF_WIDTH 42
#endif

#ifndef BW_RECOG_CLOTH_CENTER_HALF_HEIGHT
#define BW_RECOG_CLOTH_CENTER_HALF_HEIGHT 32
#endif

#pragma endregion

#pragma region C. 现场常调：处理有效区与采光

// [先调] 拿到单帧后保留的处理区间：[Y_MIN, Y_MAX)。
#ifndef BW_RECOG_PROCESS_KEEP_Y_MIN
#define BW_RECOG_PROCESS_KEEP_Y_MIN 30
#endif

#ifndef BW_RECOG_PROCESS_KEEP_Y_MAX
#define BW_RECOG_PROCESS_KEEP_Y_MAX 161
#endif

// [一般别动] 五点采光目标点数。
#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_POINT_COUNT
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_POINT_COUNT 5
#endif

#pragma endregion

#pragma region D. 现场常调：识别结果保持

// [谨慎调] 成功识别后短暂丢目标时保持上次成功结果的时间。
#ifndef BW_RECOG_SIGN_LOSS_HOLD_MS
#define BW_RECOG_SIGN_LOSS_HOLD_MS 200
#endif

// [谨慎调] 红砖 b/bl/br 短暂丢失时的输出保持帧数。
#ifndef BW_RECOG_BRICK_LOSS_HOLD_FRAMES
#define BW_RECOG_BRICK_LOSS_HOLD_FRAMES 1
#endif

// [谨慎调] 已看到标识块后，边线或红色短暂丢失时保持 u 的时间。
#ifndef BW_RECOG_U_LOSS_HOLD_MS
#define BW_RECOG_U_LOSS_HOLD_MS 100
#endif

#pragma endregion

#pragma region E. 现场常调：红块搜索带与边界

// [一般别动] marker/红砖正式触发带上边界。
#ifndef BW_RECOG_TRIGGER_SEARCH_Y_MIN
#define BW_RECOG_TRIGGER_SEARCH_Y_MIN 60
#endif

// [先调] 达到触发 y 后，正式 marker ROI 向上补取的像素；不改变 y=60 的触发时机。
#ifndef BW_RECOG_MARKER_ROI_TOP_EXPAND_PIXELS
#define BW_RECOG_MARKER_ROI_TOP_EXPAND_PIXELS 16
#endif

// [开关] marker、提前减速红块和红砖的完整候选中心只允许位于指定 x 比例区间。
#ifndef BW_RECOG_RED_IMAGE_X_GATE_ENABLE
#define BW_RECOG_RED_IMAGE_X_GATE_ENABLE 1
#endif

// [先调] 候选中心允许参与检测的画面 x 比例范围；门控不裁剪红色连通块。
#ifndef BW_RECOG_RED_IMAGE_X_MIN_RATIO
#define BW_RECOG_RED_IMAGE_X_MIN_RATIO 0.20f
#endif

#ifndef BW_RECOG_RED_IMAGE_X_MAX_RATIO
#define BW_RECOG_RED_IMAGE_X_MAX_RATIO 0.80f
#endif

// [开关] 红色候选靠近左右门控边界时启用滞回，防止候选中心抖动造成帧间反复允许/屏蔽。
#ifndef BW_RECOG_RED_IMAGE_X_GATE_HYSTERESIS_ENABLE
#define BW_RECOG_RED_IMAGE_X_GATE_HYSTERESIS_ENABLE 1
#endif

// [先调] 门控命中后向画面边缘临时放宽的像素数；320 宽下左界约从 64 放宽到 55。
#ifndef BW_RECOG_RED_IMAGE_X_GATE_HYSTERESIS_PIXELS
#define BW_RECOG_RED_IMAGE_X_GATE_HYSTERESIS_PIXELS 9
#endif

// [谨慎调] 仅用于提前发 u / 减速的前置红色检测带上边界。
#ifndef BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN
#define BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN 40
#endif

// [开关] 40~60 前置红色只提前发 u 减速；关闭后不影响 60~160 正式识别。
#ifndef BW_RECOG_EARLY_SLOWDOWN_ENABLE
#define BW_RECOG_EARLY_SLOWDOWN_ENABLE 1
#endif

// [先调] 白赛道左右边线迷宫法寻线最小 y。
#ifndef BW_RECOG_TRACK_BOUNDARY_Y_MIN
#define BW_RECOG_TRACK_BOUNDARY_Y_MIN BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN
#endif

// [先调] 红砖正式判定搜索带上边界；红砖不走 u 减速，命中后直接输出 b/bl/br。
#ifndef BW_RECOG_BRICK_SEARCH_Y_MIN
#define BW_RECOG_BRICK_SEARCH_Y_MIN BW_RECOG_TRIGGER_SEARCH_Y_MIN
#endif

// [开关] CIRCLE_RUNNING 内启用更严格的 marker 触发质量门控。
#ifndef BW_RECOG_CIRCLE_MARKER_QUALITY_GATE_ENABLE
#define BW_RECOG_CIRCLE_MARKER_QUALITY_GATE_ENABLE 1
#endif

// [先调] 环岛内 marker 红块底边至少到达该 y，才允许累计稳定帧。
#ifndef BW_RECOG_CIRCLE_TRIGGER_BOTTOM_Y_MIN
#define BW_RECOG_CIRCLE_TRIGGER_BOTTOM_Y_MIN 80
#endif

// [先调] 环岛内 marker 红块底边到达该 y 后，不再等待第二个稳定帧。
#ifndef BW_RECOG_CIRCLE_TRIGGER_IMMEDIATE_BOTTOM_Y
#define BW_RECOG_CIRCLE_TRIGGER_IMMEDIATE_BOTTOM_Y 95
#endif

// [先调] 未达到立即触发 y 时，连续满足位置条件的帧数。
#ifndef BW_RECOG_CIRCLE_TRIGGER_STABLE_FRAMES
#define BW_RECOG_CIRCLE_TRIGGER_STABLE_FRAMES 2
#endif

// [一般别动] 环岛横向门控从远端到近端的线性插值 y 范围。
#ifndef BW_RECOG_CIRCLE_X_GATE_FAR_Y
#define BW_RECOG_CIRCLE_X_GATE_FAR_Y 75
#endif

#ifndef BW_RECOG_CIRCLE_X_GATE_NEAR_Y
#define BW_RECOG_CIRCLE_X_GATE_NEAR_Y 110
#endif

// [先调] 环岛远端只允许画面中央 30%~70%，近端恢复普通 20%~80%。
#ifndef BW_RECOG_CIRCLE_X_GATE_FAR_MIN_RATIO
#define BW_RECOG_CIRCLE_X_GATE_FAR_MIN_RATIO 0.30f
#endif

#ifndef BW_RECOG_CIRCLE_X_GATE_FAR_MAX_RATIO
#define BW_RECOG_CIRCLE_X_GATE_FAR_MAX_RATIO 0.70f
#endif

#ifndef BW_RECOG_CIRCLE_X_GATE_NEAR_MIN_RATIO
#define BW_RECOG_CIRCLE_X_GATE_NEAR_MIN_RATIO 0.20f
#endif

#ifndef BW_RECOG_CIRCLE_X_GATE_NEAR_MAX_RATIO
#define BW_RECOG_CIRCLE_X_GATE_NEAR_MAX_RATIO 0.80f
#endif

#pragma endregion

#pragma region F. 现场常调：模型置信度阈值

#ifndef BW_RECOG_SINGLE_FRAME_HIGH_CONF_TOP1_THRESHOLD
#define BW_RECOG_SINGLE_FRAME_HIGH_CONF_TOP1_THRESHOLD 0.90f
#endif

#ifndef BW_RECOG_SINGLE_FRAME_HIGH_CONF_MARGIN_THRESHOLD
#define BW_RECOG_SINGLE_FRAME_HIGH_CONF_MARGIN_THRESHOLD 0.70f
#endif


#pragma region G. 几乎不调的参数

// --- 顶层默认与模型 ---

// [一般别动] 识别链编译期默认开关，可被 --recognition / --no-recognition 覆盖。
#ifndef BW_ENABLE_RECOGNITION
#define BW_ENABLE_RECOGNITION 1
#endif

// --- ROI 拍摄模式 ---

// [先调] ROI 拍摄模式编译期默认开关，可被 --roi-capture / --mode 覆盖。
#ifndef BW_ENABLE_ROI_CAPTURE_MODE
#define BW_ENABLE_ROI_CAPTURE_MODE 0
#endif

// [先调] ROI 拍摄模式输出边长，默认跟当前模型输入尺寸一致。
#ifndef BW_RECOG_ROI_CAPTURE_OUTPUT_SIZE
#define BW_RECOG_ROI_CAPTURE_OUTPUT_SIZE 32
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SEND_HOST
#define BW_RECOG_ROI_CAPTURE_SEND_HOST ""
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SEND_PORT
#define BW_RECOG_ROI_CAPTURE_SEND_PORT 5001
#endif

#ifndef BW_RECOG_ROI_CAPTURE_BURST_COUNT
#define BW_RECOG_ROI_CAPTURE_BURST_COUNT 10
#endif

#ifndef BW_RECOG_FULLFRAME_CAPTURE_BURST_COUNT
#define BW_RECOG_FULLFRAME_CAPTURE_BURST_COUNT 10
#endif

#ifndef BW_RECOG_CAPTURE_PNG_COMPRESSION
#define BW_RECOG_CAPTURE_PNG_COMPRESSION 1
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SOCKET_TIMEOUT_MS
#define BW_RECOG_ROI_CAPTURE_SOCKET_TIMEOUT_MS 1500
#endif

// --- 相机底层与固定参数 ---

#ifndef BW_RECOG_CAMERA_FRAME_WIDTH
#define BW_RECOG_CAMERA_FRAME_WIDTH 320
#endif

#ifndef BW_RECOG_CAMERA_FRAME_HEIGHT
#define BW_RECOG_CAMERA_FRAME_HEIGHT 240
#endif

#ifndef BW_RECOG_TRANSFORM_TABLE_WIDTH
#define BW_RECOG_TRANSFORM_TABLE_WIDTH 320
#endif

#ifndef BW_RECOG_TRANSFORM_TABLE_HEIGHT
#define BW_RECOG_TRANSFORM_TABLE_HEIGHT 240
#endif

#ifndef BW_RECOG_CAMERA_FPS
// #define BW_RECOG_CAMERA_FPS 20
#define BW_RECOG_CAMERA_FPS 120
#endif

#ifndef BW_RECOG_CAMERA_TRY_0CPU_MJPG
#define BW_RECOG_CAMERA_TRY_0CPU_MJPG 1
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_ENABLE
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_ENABLE 1
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_CONFIG_FILE
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_CONFIG_FILE "recognition_startup_lighting.cfg"
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_SETTLE_FRAMES
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_SETTLE_FRAMES 12
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_EXPOSURE
#define BW_RECOG_CAMERA_USE_MANUAL_EXPOSURE 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_EXPOSURE
#define BW_RECOG_CAMERA_MANUAL_EXPOSURE 100
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_GAIN
#define BW_RECOG_CAMERA_USE_MANUAL_GAIN 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_GAIN
#define BW_RECOG_CAMERA_MANUAL_GAIN 16.0
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_WHITE_BALANCE
#define BW_RECOG_CAMERA_USE_MANUAL_WHITE_BALANCE 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_WB_BLUE
#define BW_RECOG_CAMERA_MANUAL_WB_BLUE 4600.0
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_WB_RED
#define BW_RECOG_CAMERA_MANUAL_WB_RED 4600.0
#endif

// --- 帧获取与主循环 ---

#ifndef BW_RECOG_LATEST_FRAME_ENABLE
#define BW_RECOG_LATEST_FRAME_ENABLE 1
#endif

#ifndef BW_RECOG_LATEST_FRAME_WAIT_FIRST_FRAME_MS
#define BW_RECOG_LATEST_FRAME_WAIT_FIRST_FRAME_MS 500
#endif

#ifndef BW_RECOG_LOOP_TARGET_FPS
// #define BW_RECOG_LOOP_TARGET_FPS 20
#define BW_RECOG_LOOP_TARGET_FPS 120
#endif

#ifndef BW_RECOG_LOOP_FPS_NORMAL
// #define BW_RECOG_LOOP_FPS_NORMAL 10
#define BW_RECOG_LOOP_FPS_NORMAL 120
#endif

#ifndef BW_RECOG_LOOP_FPS_CANDIDATE
// #define BW_RECOG_LOOP_FPS_CANDIDATE 25
#define BW_RECOG_LOOP_FPS_CANDIDATE 120
#endif

#ifndef BW_RECOG_LOOP_FPS_RECOGNITION
// #define BW_RECOG_LOOP_FPS_RECOGNITION 30
#define BW_RECOG_LOOP_FPS_RECOGNITION 120
#endif

#ifndef BW_RECOG_LOOP_FPS_LATCHED
#define BW_RECOG_LOOP_FPS_LATCHED 120
#endif

#ifndef BW_RECOG_IDLE_SLEEP_MS
#define BW_RECOG_IDLE_SLEEP_MS 8
#endif

#ifndef BW_RECOG_ACTIVE_SLEEP_MS
#define BW_RECOG_ACTIVE_SLEEP_MS 0
#endif

// --- 日志、图传与串口 ---

#ifndef BW_RECOG_ENABLE_PERF_LOG
#define BW_RECOG_ENABLE_PERF_LOG 0
#endif

#ifndef BW_RECOG_TEXT_LOG_ENABLE
#define BW_RECOG_TEXT_LOG_ENABLE 0
#endif

#ifndef BW_RECOG_RESULT_LOG_ENABLE
#define BW_RECOG_RESULT_LOG_ENABLE 1
#endif

#ifndef BW_RECOG_ONNX_WARMUP_RUNS
#define BW_RECOG_ONNX_WARMUP_RUNS 3
#endif

#ifndef BW_RECOG_MANUAL_MLP_COMPARE_ONNX
#define BW_RECOG_MANUAL_MLP_COMPARE_ONNX 0
#endif

#ifndef BW_RECOG_MANUAL_MLP_COMPARE_LOG_INTERVAL_MS
#define BW_RECOG_MANUAL_MLP_COMPARE_LOG_INTERVAL_MS 1000
#endif

#ifndef BW_RECOG_MANUAL_MLP_COMPARE_LOGIT_DIFF_WARN
#define BW_RECOG_MANUAL_MLP_COMPARE_LOGIT_DIFF_WARN 0.0001f
#endif

#ifndef BW_RECOG_MANUAL_MLP_COMPARE_PROB_DIFF_WARN
#define BW_RECOG_MANUAL_MLP_COMPARE_PROB_DIFF_WARN 0.0001f
#endif

#ifndef BW_RECOG_U_TO_RESULT_TIMING_LOG_ENABLE
#define BW_RECOG_U_TO_RESULT_TIMING_LOG_ENABLE 0
#endif

#ifndef BW_RECOG_LIGHTWEIGHT_RED_PREFILTER_ENABLE
#define BW_RECOG_LIGHTWEIGHT_RED_PREFILTER_ENABLE 1
#endif

#ifndef BW_RECOG_TRIGGER_FRAME_INFER_ENABLE
#define BW_RECOG_TRIGGER_FRAME_INFER_ENABLE 1
#endif

#ifndef BW_RECOG_TRIGGER_FRAME_EARLY_U_SEND_ENABLE
#define BW_RECOG_TRIGGER_FRAME_EARLY_U_SEND_ENABLE 1
#endif

#ifndef BW_RECOG_VERBOSE_LOG
#define BW_RECOG_VERBOSE_LOG 0
#endif

#ifndef BW_STREAM_PUBLISH_INTERVAL_FRAMES
#define BW_STREAM_PUBLISH_INTERVAL_FRAMES 2
#endif

#ifndef BW_STREAM_MAX_WIDTH
#define BW_STREAM_MAX_WIDTH 400
#endif

#ifndef BW_STREAM_JPEG_QUALITY
#define BW_STREAM_JPEG_QUALITY 60
#endif

#ifndef BW_STREAM_CROP_MAX_Y
#define BW_STREAM_CROP_MAX_Y 200
#endif

#ifndef BW_RECOG_ROI_PREVIEW_SIZE
#define BW_RECOG_ROI_PREVIEW_SIZE 112
#endif

#ifndef BW_BOARD_COMM_INIT_RETRY_TIMES
#define BW_BOARD_COMM_INIT_RETRY_TIMES 10
#endif

#ifndef BW_BOARD_COMM_INIT_RETRY_INTERVAL_MS
#define BW_BOARD_COMM_INIT_RETRY_INTERVAL_MS 1000
#endif

#ifndef BW_RECOG_STATE_HEARTBEAT_INTERVAL_MS
#define BW_RECOG_STATE_HEARTBEAT_INTERVAL_MS 50
#endif

// 运行板环岛识别门控。BLOCK 时识别板清空整条识别链并只输出 n。
#ifndef BW_RECOG_CIRCLE_GATE_ENABLE
#define BW_RECOG_CIRCLE_GATE_ENABLE 1
#endif

// BLOCK 后是否允许因门控心跳超时自动恢复 ALLOW。
// 设为 0：关闭超时自动放行，必须收到运行板明确 ALLOW 才解除环岛门控。
#ifndef BW_RECOG_CIRCLE_GATE_STALE_MS
#define BW_RECOG_CIRCLE_GATE_STALE_MS 0
#endif

// 十字内无边线提前识别。只在收到运行板 ALLOW_CROSSING 时生效；
// 使用严格红阈值和画面中心门控，推理结果锁存到退出十字后再发送。
#ifndef BW_RECOG_CROSSING_NO_LINE_ENABLE
#define BW_RECOG_CROSSING_NO_LINE_ENABLE 1
#endif

// --- 概率阈值、ROI 几何与相对阈值 ---

#ifndef BW_RECOG_DECISION_TOP1_THRESHOLD
#ifdef BW_RECOG_DECISION_TOP1_AVG_THRESHOLD
#define BW_RECOG_DECISION_TOP1_THRESHOLD BW_RECOG_DECISION_TOP1_AVG_THRESHOLD
#else
#define BW_RECOG_DECISION_TOP1_THRESHOLD 0.3
#endif
#endif

#ifndef BW_RECOG_DECISION_MARGIN_THRESHOLD
#define BW_RECOG_DECISION_MARGIN_THRESHOLD 0.01f
#endif

#ifndef BW_RECOG_ADAPTIVE_TWO_FRAME_ENABLE
#define BW_RECOG_ADAPTIVE_TWO_FRAME_ENABLE 1
#endif


#ifndef BW_RECOG_ADAPTIVE_TWO_FRAME_MAX_BAD_FRAMES
#define BW_RECOG_ADAPTIVE_TWO_FRAME_MAX_BAD_FRAMES 3
#endif

#ifndef BW_RECOG_TRIGGER_SEARCH_Y_MAX
#define BW_RECOG_TRIGGER_SEARCH_Y_MAX 160
#endif

#ifndef BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MAX
#define BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MAX BW_RECOG_TRIGGER_SEARCH_Y_MAX
#endif

#ifndef BW_RECOG_BRICK_SEARCH_Y_MAX
#define BW_RECOG_BRICK_SEARCH_Y_MAX BW_RECOG_TRIGGER_SEARCH_Y_MAX
#endif

#ifndef BW_RECOG_WHITE_REFERENCE_ROW_Y
#define BW_RECOG_WHITE_REFERENCE_ROW_Y 160
#endif

#ifndef BW_RECOG_LOOSE_RED_MIN_AREA
#define BW_RECOG_LOOSE_RED_MIN_AREA 200
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_ENABLE
#define BW_RECOG_WHITE_REF_NORMALIZE_ENABLE 1
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_TARGET_LUMA
#define BW_RECOG_WHITE_REF_NORMALIZE_TARGET_LUMA 200.0f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MIN
#define BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MIN 0.75f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MAX
#define BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MAX 1.30f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MIN
#define BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MIN 0.85f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MAX
#define BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MAX 1.15f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_ALPHA
#define BW_RECOG_WHITE_REF_NORMALIZE_ALPHA 0.20f
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MAX_SATURATION
#define BW_RECOG_WHITE_REF_SEED_MAX_SATURATION 90
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MIN_VALUE
#define BW_RECOG_WHITE_REF_SEED_MIN_VALUE 110
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MIN_RGB
#define BW_RECOG_WHITE_REF_SEED_MIN_RGB 95
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MAX_CHANNEL_DIFF
#define BW_RECOG_WHITE_REF_SEED_MAX_CHANNEL_DIFF 90
#endif

#ifndef BW_RECOG_WHITE_REF_STATS_HALF_HEIGHT
#define BW_RECOG_WHITE_REF_STATS_HALF_HEIGHT 2
#endif

// [一般别动] 白参考统计/归一化 gain 的真实更新帧间隔；1 表示每帧更新。
#ifndef BW_RECOG_WHITE_REF_STATS_UPDATE_INTERVAL_FRAMES
#define BW_RECOG_WHITE_REF_STATS_UPDATE_INTERVAL_FRAMES 3
#endif

#ifndef BW_RECOG_TRACK_WHITE_MIN_LUMA_RATIO
#define BW_RECOG_TRACK_WHITE_MIN_LUMA_RATIO 0.70f
#endif

#ifndef BW_RECOG_TRACK_WHITE_MIN_RGB_RATIO
#define BW_RECOG_TRACK_WHITE_MIN_RGB_RATIO 0.66f
#endif

#ifndef BW_RECOG_TRACK_WHITE_MAX_CHANNEL_DIFF_RATIO
#define BW_RECOG_TRACK_WHITE_MAX_CHANNEL_DIFF_RATIO 0.16f
#endif

#ifndef BW_RECOG_TRACK_MAZE_MAX_STEPS
#define BW_RECOG_TRACK_MAZE_MAX_STEPS 300
#endif

// [一般别动] 识别板白带迷宫爬线按需缓存半窗口；2 表示每次只缓存 x-2..x+2。
#ifndef BW_RECOG_TRACK_LAZY_MASK_HALF_WINDOW
#define BW_RECOG_TRACK_LAZY_MASK_HALF_WINDOW 2
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_SCORE_RELATIVE_RATIO 0.42f
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_MIN_R_RELATIVE_RATIO 0.40f
#endif

#ifndef BW_RECOG_TASK_RED_DOM_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_DOM_RELATIVE_RATIO 0.18f
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_MIN_FLOOR
#define BW_RECOG_TASK_RED_SCORE_MIN_FLOOR 40
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_FLOOR
#define BW_RECOG_TASK_RED_MIN_R_FLOOR 40
#endif

#ifndef BW_RECOG_TASK_RED_DOM_MIN_FLOOR
#define BW_RECOG_TASK_RED_DOM_MIN_FLOOR 12
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_MAX_CEIL
#define BW_RECOG_TASK_RED_SCORE_MAX_CEIL 180
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_MAX_CEIL
#define BW_RECOG_TASK_RED_MIN_R_MAX_CEIL 140
#endif

#ifndef BW_RECOG_TASK_RED_DOM_MAX_CEIL
#define BW_RECOG_TASK_RED_DOM_MAX_CEIL 120
#endif

#ifndef BW_RECOG_CLOTH_GREEN_H_MIN
#define BW_RECOG_CLOTH_GREEN_H_MIN 35
#endif

#ifndef BW_RECOG_CLOTH_GREEN_H_MAX
#define BW_RECOG_CLOTH_GREEN_H_MAX 90
#endif

#ifndef BW_RECOG_CLOTH_GREEN_S_MIN
#define BW_RECOG_CLOTH_GREEN_S_MIN 55
#endif

#ifndef BW_RECOG_CLOTH_GREEN_V_MIN
#define BW_RECOG_CLOTH_GREEN_V_MIN 45
#endif

#ifndef BW_RECOG_CLOTH_GREEN_DOM_MIN
#define BW_RECOG_CLOTH_GREEN_DOM_MIN 18
#endif

#ifndef BW_RECOG_CLOTH_GREEN_MIN_PIXELS
#define BW_RECOG_CLOTH_GREEN_MIN_PIXELS 90
#endif

#ifndef BW_RECOG_CLOTH_GREEN_MIN_RATIO
#define BW_RECOG_CLOTH_GREEN_MIN_RATIO 0.035f
#endif

// 红砖带相对边界向赛道外侧扩张的像素。
#ifndef BW_RECOG_TRACK_BRICK_OUTER_EXPAND_PIXELS
#define BW_RECOG_TRACK_BRICK_OUTER_EXPAND_PIXELS 8
#endif

// 红砖带向赛道内侧的最大像素；y=60 为 0，向下线性增加至该值。
#ifndef BW_RECOG_TRACK_BRICK_INNER_MAX_PIXELS
#define BW_RECOG_TRACK_BRICK_INNER_MAX_PIXELS 5
#endif

// 红砖带单行最少连续严格红像素；只过滤孤立噪点，不是面积阈值。
#ifndef BW_RECOG_TRACK_BRICK_MIN_HORIZONTAL_RUN_PIXELS
#define BW_RECOG_TRACK_BRICK_MIN_HORIZONTAL_RUN_PIXELS 2
#endif

#pragma endregion

#endif
