#ifndef _USER_COMMON_H_
#define _USER_COMMON_H_

// 识别板统一配置入口
// -----------------------------------------------------------------------------
// 当前主链口径：
// - 相机输入固定按 320x240 彩色图处理。
// - 软件层只保留 y=30..160 的有效区域，其余区域拿到单帧后直接清黑。
// - ROI 几何主链基于 white_reference_row_y=160 的白红参考包络、白带边线迷宫法、
//   严格红掩码和曲边赛道区域判定。
// - 六小类模型可在板端聚合成 weapon/supply/vehicle 三大类输出，串口仍输出 w/s/v。
//
// 组织原则：
// - 前面只放现场常调参数。
// - 自己不确定怎么调、通常不该动的参数，统一放到最后的“几乎不调”区。

#pragma region A. 现场常调：运行模式

// [先调] 图传编译期默认开关，可被 --stream / --no-stream 覆盖。
#ifndef BW_ENABLE_STREAM
#define BW_ENABLE_STREAM 0
#endif

// [先调] 1：上电后等待按 c 启动；0：上电即持续运行识别链。
#ifndef BW_RECOG_REQUIRE_MANUAL_START
#define BW_RECOG_REQUIRE_MANUAL_START 0
#endif

#pragma endregion

#pragma region B. 现场常调：处理有效区与采光

// [先调] 拿到单帧后保留的处理区间：[Y_MIN, Y_MAX)。
#ifndef BW_RECOG_PROCESS_KEEP_Y_MIN
#define BW_RECOG_PROCESS_KEEP_Y_MIN 30
#endif

#ifndef BW_RECOG_PROCESS_KEEP_Y_MAX
#define BW_RECOG_PROCESS_KEEP_Y_MAX 161
#endif

// [一般别动] 五点采光目标点数。
#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_POINT_COUNT
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_POINT_COUNT 5
#endif

#pragma endregion

#pragma region C. 现场常调：识别帧数与决策保持

#ifndef BW_RECOG_MIN_VALID_FRAMES
#define BW_RECOG_MIN_VALID_FRAMES 2
#endif

#ifndef BW_RECOG_MAX_VALID_FRAMES
#define BW_RECOG_MAX_VALID_FRAMES 2
#endif

// [谨慎调] 成功识别后短暂丢目标时保持上次成功结果的时间。
#ifndef BW_RECOG_SIGN_LOSS_HOLD_MS
#define BW_RECOG_SIGN_LOSS_HOLD_MS 200
#endif

#pragma endregion

#pragma region D. 现场常调：红块搜索带与边界

// [一般别动] 正式红块搜索带上边界。
#ifndef BW_RECOG_TRIGGER_SEARCH_Y_MIN
#define BW_RECOG_TRIGGER_SEARCH_Y_MIN 40
#endif

// [谨慎调] 仅用于提前发 u / 减速的前置红色检测带上边界。
#ifndef BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN
#define BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN 40
#endif

// [先调] 白赛道左右边线迷宫法寻线最小 y。
#ifndef BW_RECOG_TRACK_BOUNDARY_Y_MIN
#define BW_RECOG_TRACK_BOUNDARY_Y_MIN BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MIN
#endif

// [先调] 边界外侧仍视为红砖带的扩张像素。
#ifndef BW_RECOG_TRACK_BRICK_OUTER_EXPAND_PIXELS
#define BW_RECOG_TRACK_BRICK_OUTER_EXPAND_PIXELS 8
#endif

#pragma endregion

#pragma region E. 几乎不调的参数

// --- 顶层默认与模型 ---

// [一般别动] 识别链编译期默认开关，可被 --recognition / --no-recognition 覆盖。
#ifndef BW_ENABLE_RECOGNITION
#define BW_ENABLE_RECOGNITION 1
#endif

// [一般别动] 模型模式枚举。
#ifndef BW_RECOG_MODEL_VARIANT_RGB64
#define BW_RECOG_MODEL_VARIANT_RGB64 0
#endif

#ifndef BW_RECOG_MODEL_VARIANT_GRAYRED32
#define BW_RECOG_MODEL_VARIANT_GRAYRED32 1
#endif

#ifndef BW_RECOG_MODEL_VARIANT_GRAY32_SUBCLASS
#define BW_RECOG_MODEL_VARIANT_GRAY32_SUBCLASS 2
#endif

#ifndef BW_RECOG_MODEL_VARIANT_RGB32_SUBCLASS
#define BW_RECOG_MODEL_VARIANT_RGB32_SUBCLASS 3
#endif

// 0：旧 64x64 RGB；1：32x32 gray+red_dom；2：32x32 gray 六小类；3：32x32 RGB 六小类。
#ifndef BW_RECOG_MODEL_VARIANT
#define BW_RECOG_MODEL_VARIANT BW_RECOG_MODEL_VARIANT_RGB32_SUBCLASS
#endif

// --- ROI 拍摄模式 ---

// [先调] ROI 拍摄模式编译期默认开关，可被 --roi-capture / --mode 覆盖。
#ifndef BW_ENABLE_ROI_CAPTURE_MODE
#define BW_ENABLE_ROI_CAPTURE_MODE 0
#endif

// [先调] ROI 拍摄模式输出边长，默认跟当前模型输入尺寸一致。
#ifndef BW_RECOG_ROI_CAPTURE_OUTPUT_SIZE
#if (BW_RECOG_MODEL_VARIANT == BW_RECOG_MODEL_VARIANT_RGB64)
#define BW_RECOG_ROI_CAPTURE_OUTPUT_SIZE 64
#else
#define BW_RECOG_ROI_CAPTURE_OUTPUT_SIZE 32
#endif
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SEND_HOST
#define BW_RECOG_ROI_CAPTURE_SEND_HOST ""
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SEND_PORT
#define BW_RECOG_ROI_CAPTURE_SEND_PORT 5001
#endif

#ifndef BW_RECOG_ROI_CAPTURE_BURST_COUNT
#define BW_RECOG_ROI_CAPTURE_BURST_COUNT 10
#endif

#ifndef BW_RECOG_ROI_CAPTURE_JPEG_QUALITY
#define BW_RECOG_ROI_CAPTURE_JPEG_QUALITY 95
#endif

#ifndef BW_RECOG_ROI_CAPTURE_SOCKET_TIMEOUT_MS
#define BW_RECOG_ROI_CAPTURE_SOCKET_TIMEOUT_MS 1500
#endif

// --- 相机底层与固定参数 ---

#ifndef BW_RECOG_CAMERA_FRAME_WIDTH
#define BW_RECOG_CAMERA_FRAME_WIDTH 320
#endif

#ifndef BW_RECOG_CAMERA_FRAME_HEIGHT
#define BW_RECOG_CAMERA_FRAME_HEIGHT 240
#endif

#ifndef BW_RECOG_TRANSFORM_TABLE_WIDTH
#define BW_RECOG_TRANSFORM_TABLE_WIDTH 320
#endif

#ifndef BW_RECOG_TRANSFORM_TABLE_HEIGHT
#define BW_RECOG_TRANSFORM_TABLE_HEIGHT 240
#endif

#ifndef BW_RECOG_CAMERA_FPS
// #define BW_RECOG_CAMERA_FPS 20
#define BW_RECOG_CAMERA_FPS 120
#endif

#ifndef BW_RECOG_CAMERA_TRY_0CPU_MJPG
#define BW_RECOG_CAMERA_TRY_0CPU_MJPG 1
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_ENABLE
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_ENABLE 1
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_CONFIG_FILE
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_CONFIG_FILE "recognition_startup_lighting.cfg"
#endif

#ifndef BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_SETTLE_FRAMES
#define BW_RECOG_STARTUP_FIVE_POINT_LIGHTING_SETTLE_FRAMES 12
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_EXPOSURE
#define BW_RECOG_CAMERA_USE_MANUAL_EXPOSURE 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_EXPOSURE
#define BW_RECOG_CAMERA_MANUAL_EXPOSURE 100
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_GAIN
#define BW_RECOG_CAMERA_USE_MANUAL_GAIN 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_GAIN
#define BW_RECOG_CAMERA_MANUAL_GAIN 16.0
#endif

#ifndef BW_RECOG_CAMERA_USE_MANUAL_WHITE_BALANCE
#define BW_RECOG_CAMERA_USE_MANUAL_WHITE_BALANCE 1
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_WB_BLUE
#define BW_RECOG_CAMERA_MANUAL_WB_BLUE 4600.0
#endif

#ifndef BW_RECOG_CAMERA_MANUAL_WB_RED
#define BW_RECOG_CAMERA_MANUAL_WB_RED 4600.0
#endif

// --- 帧获取与主循环 ---

#ifndef BW_RECOG_LATEST_FRAME_ENABLE
#define BW_RECOG_LATEST_FRAME_ENABLE 1
#endif

#ifndef BW_RECOG_LATEST_FRAME_WAIT_FIRST_FRAME_MS
#define BW_RECOG_LATEST_FRAME_WAIT_FIRST_FRAME_MS 500
#endif

#ifndef BW_RECOG_LOOP_TARGET_FPS
// #define BW_RECOG_LOOP_TARGET_FPS 20
#define BW_RECOG_LOOP_TARGET_FPS 120
#endif

#ifndef BW_RECOG_LOOP_FPS_NORMAL
// #define BW_RECOG_LOOP_FPS_NORMAL 10
#define BW_RECOG_LOOP_FPS_NORMAL 120
#endif

#ifndef BW_RECOG_LOOP_FPS_CANDIDATE
// #define BW_RECOG_LOOP_FPS_CANDIDATE 25
#define BW_RECOG_LOOP_FPS_CANDIDATE 120
#endif

#ifndef BW_RECOG_LOOP_FPS_RECOGNITION
// #define BW_RECOG_LOOP_FPS_RECOGNITION 30
#define BW_RECOG_LOOP_FPS_RECOGNITION 120
#endif

#ifndef BW_RECOG_LOOP_FPS_LATCHED
#define BW_RECOG_LOOP_FPS_LATCHED 120
#endif

#ifndef BW_RECOG_IDLE_SLEEP_MS
#define BW_RECOG_IDLE_SLEEP_MS 8
#endif

#ifndef BW_RECOG_ACTIVE_SLEEP_MS
#define BW_RECOG_ACTIVE_SLEEP_MS 0
#endif

// --- 日志、图传与串口 ---

#ifndef BW_RECOG_ENABLE_PERF_LOG
#define BW_RECOG_ENABLE_PERF_LOG 0
#endif

#ifndef BW_RECOG_TEXT_LOG_ENABLE
#define BW_RECOG_TEXT_LOG_ENABLE 0
#endif

#ifndef BW_RECOG_RESULT_LOG_ENABLE
#define BW_RECOG_RESULT_LOG_ENABLE 1
#endif

#ifndef BW_RECOG_VERBOSE_LOG
#define BW_RECOG_VERBOSE_LOG 0
#endif

#ifndef BW_STREAM_PUBLISH_INTERVAL_FRAMES
#define BW_STREAM_PUBLISH_INTERVAL_FRAMES 2
#endif

#ifndef BW_STREAM_MAX_WIDTH
#define BW_STREAM_MAX_WIDTH 400
#endif

#ifndef BW_STREAM_JPEG_QUALITY
#define BW_STREAM_JPEG_QUALITY 60
#endif

#ifndef BW_STREAM_CROP_MAX_Y
#define BW_STREAM_CROP_MAX_Y 200
#endif

#ifndef BW_RECOG_ROI_PREVIEW_SIZE
#define BW_RECOG_ROI_PREVIEW_SIZE 112
#endif

#ifndef BW_BOARD_COMM_INIT_RETRY_TIMES
#define BW_BOARD_COMM_INIT_RETRY_TIMES 10
#endif

#ifndef BW_BOARD_COMM_INIT_RETRY_INTERVAL_MS
#define BW_BOARD_COMM_INIT_RETRY_INTERVAL_MS 1000
#endif

#ifndef BW_RECOG_STATE_HEARTBEAT_INTERVAL_MS
#define BW_RECOG_STATE_HEARTBEAT_INTERVAL_MS 50
#endif

// --- 概率阈值、ROI 几何与相对阈值 ---

#ifndef BW_RECOG_DECISION_TOP1_AVG_THRESHOLD
#define BW_RECOG_DECISION_TOP1_AVG_THRESHOLD 0.3
#endif

#ifndef BW_RECOG_DECISION_MARGIN_THRESHOLD
#define BW_RECOG_DECISION_MARGIN_THRESHOLD 0.01f
#endif

#ifndef BW_RECOG_TRIGGER_SEARCH_Y_MAX
#define BW_RECOG_TRIGGER_SEARCH_Y_MAX 160
#endif

#ifndef BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MAX
#define BW_RECOG_SLOWDOWN_TRIGGER_SEARCH_Y_MAX BW_RECOG_TRIGGER_SEARCH_Y_MAX
#endif

#ifndef BW_RECOG_RED_MASK_MAX_Y
#define BW_RECOG_RED_MASK_MAX_Y 160
#endif

#ifndef BW_RECOG_WHITE_REFERENCE_ROW_Y
#define BW_RECOG_WHITE_REFERENCE_ROW_Y 160
#endif

#ifndef BW_RECOG_RED_MIN_AREA
#define BW_RECOG_RED_MIN_AREA 500
#endif

#ifndef BW_RECOG_LOOSE_RED_MIN_AREA
#define BW_RECOG_LOOSE_RED_MIN_AREA 200
#endif

#ifndef BW_RECOG_TRIGGER_IPM_RECT_ENABLE
#define BW_RECOG_TRIGGER_IPM_RECT_ENABLE 1
#endif

#ifndef BW_RECOG_TRIGGER_IPM_MIN_WIDTH_HEIGHT_RATIO
#define BW_RECOG_TRIGGER_IPM_MIN_WIDTH_HEIGHT_RATIO 1.30f
#endif

#ifndef BW_RECOG_ROI_LOW_INFO_FILTER_ENABLE
#define BW_RECOG_ROI_LOW_INFO_FILTER_ENABLE 0
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_ENABLE
#define BW_RECOG_WHITE_REF_NORMALIZE_ENABLE 1
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_TARGET_LUMA
#define BW_RECOG_WHITE_REF_NORMALIZE_TARGET_LUMA 200.0f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MIN
#define BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MIN 0.75f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MAX
#define BW_RECOG_WHITE_REF_NORMALIZE_LUMA_GAIN_MAX 1.30f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MIN
#define BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MIN 0.85f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MAX
#define BW_RECOG_WHITE_REF_NORMALIZE_WB_GAIN_MAX 1.15f
#endif

#ifndef BW_RECOG_WHITE_REF_NORMALIZE_ALPHA
#define BW_RECOG_WHITE_REF_NORMALIZE_ALPHA 0.20f
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MAX_SATURATION
#define BW_RECOG_WHITE_REF_SEED_MAX_SATURATION 90
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MIN_VALUE
#define BW_RECOG_WHITE_REF_SEED_MIN_VALUE 110
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MIN_RGB
#define BW_RECOG_WHITE_REF_SEED_MIN_RGB 95
#endif

#ifndef BW_RECOG_WHITE_REF_SEED_MAX_CHANNEL_DIFF
#define BW_RECOG_WHITE_REF_SEED_MAX_CHANNEL_DIFF 90
#endif

#ifndef BW_RECOG_WHITE_REF_STATS_HALF_HEIGHT
#define BW_RECOG_WHITE_REF_STATS_HALF_HEIGHT 2
#endif

#ifndef BW_RECOG_TRACK_WHITE_MIN_LUMA_RATIO
#define BW_RECOG_TRACK_WHITE_MIN_LUMA_RATIO 0.70f
#endif

#ifndef BW_RECOG_TRACK_WHITE_MIN_RGB_RATIO
#define BW_RECOG_TRACK_WHITE_MIN_RGB_RATIO 0.66f
#endif

#ifndef BW_RECOG_TRACK_WHITE_MAX_CHANNEL_DIFF_RATIO
#define BW_RECOG_TRACK_WHITE_MAX_CHANNEL_DIFF_RATIO 0.16f
#endif

#ifndef BW_RECOG_TRACK_MAZE_MAX_STEPS
#define BW_RECOG_TRACK_MAZE_MAX_STEPS 300
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_SCORE_RELATIVE_RATIO 0.36f
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_MIN_R_RELATIVE_RATIO 0.36f
#endif

#ifndef BW_RECOG_TASK_RED_DOM_RELATIVE_RATIO
#define BW_RECOG_TASK_RED_DOM_RELATIVE_RATIO 0.14f
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_MIN_FLOOR
#define BW_RECOG_TASK_RED_SCORE_MIN_FLOOR 40
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_FLOOR
#define BW_RECOG_TASK_RED_MIN_R_FLOOR 40
#endif

#ifndef BW_RECOG_TASK_RED_DOM_MIN_FLOOR
#define BW_RECOG_TASK_RED_DOM_MIN_FLOOR 12
#endif

#ifndef BW_RECOG_TASK_RED_SCORE_MAX_CEIL
#define BW_RECOG_TASK_RED_SCORE_MAX_CEIL 180
#endif

#ifndef BW_RECOG_TASK_RED_MIN_R_MAX_CEIL
#define BW_RECOG_TASK_RED_MIN_R_MAX_CEIL 140
#endif

#ifndef BW_RECOG_TASK_RED_DOM_MAX_CEIL
#define BW_RECOG_TASK_RED_DOM_MAX_CEIL 120
#endif

#pragma endregion

#endif
